/* tslint:disable */
/* eslint-disable */
/**
 * Nestbox API Agents API
 * API for Nestbox Agents, control your agents
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface AdditionalAgentParameterDto
 */
export interface AdditionalAgentParameterDto {
    /**
     * 
     * @type {string}
     * @memberof AdditionalAgentParameterDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof AdditionalAgentParameterDto
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof AdditionalAgentParameterDto
     */
    'default_value': string;
    /**
     * The ID of the machine model associated with this additional parameter
     * @type {string}
     * @memberof AdditionalAgentParameterDto
     */
    'machineModelId': string;
}
/**
 * 
 * @export
 * @interface AgentParameterDto
 */
export interface AgentParameterDto {
    /**
     * 
     * @type {string}
     * @memberof AgentParameterDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof AgentParameterDto
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof AgentParameterDto
     */
    'default_value': string;
    /**
     * The ID of the machine model associated with this parameter
     * @type {string}
     * @memberof AgentParameterDto
     */
    'machineModelId': string;
}
/**
 * 
 * @export
 * @interface CreateAdditionalParameterDto
 */
export interface CreateAdditionalParameterDto {
    /**
     * The name of the additional parameter
     * @type {string}
     * @memberof CreateAdditionalParameterDto
     */
    'name': string;
    /**
     * The description of the additional parameter
     * @type {string}
     * @memberof CreateAdditionalParameterDto
     */
    'description': string;
    /**
     * The default value of the additional parameter
     * @type {string}
     * @memberof CreateAdditionalParameterDto
     */
    'default_value': string;
    /**
     * The ID of the machine model associated with this additional parameter
     * @type {string}
     * @memberof CreateAdditionalParameterDto
     */
    'machineModelId': string;
}
/**
 * 
 * @export
 * @interface CreateExamplePromptDto
 */
export interface CreateExamplePromptDto {
    /**
     * The training prompt for the example
     * @type {string}
     * @memberof CreateExamplePromptDto
     */
    'trainingPrompt': string;
    /**
     * The answer for the training prompt
     * @type {string}
     * @memberof CreateExamplePromptDto
     */
    'promptAnswer': string;
    /**
     * The ID of the machine model associated with this example
     * @type {string}
     * @memberof CreateExamplePromptDto
     */
    'machineModelId': string;
}
/**
 * 
 * @export
 * @interface CreateMachineAgentDto
 */
export interface CreateMachineAgentDto {
    /**
     * 
     * @type {string}
     * @memberof CreateMachineAgentDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CreateMachineAgentDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMachineAgentDto
     */
    'entryFunctionName'?: string;
    /**
     * 
     * @type {Array<AgentParameterDto>}
     * @memberof CreateMachineAgentDto
     */
    'parameters'?: Array<AgentParameterDto>;
    /**
     * 
     * @type {Array<AdditionalAgentParameterDto>}
     * @memberof CreateMachineAgentDto
     */
    'additionalParameters'?: Array<AdditionalAgentParameterDto>;
}
/**
 * 
 * @export
 * @interface CreateMachineModelDto
 */
export interface CreateMachineModelDto {
    /**
     * The name of the machine model
     * @type {string}
     * @memberof CreateMachineModelDto
     */
    'name': string;
    /**
     * The description of the machine model
     * @type {string}
     * @memberof CreateMachineModelDto
     */
    'description': string;
    /**
     * The prompt associated with the machine model
     * @type {string}
     * @memberof CreateMachineModelDto
     */
    'prompt': string;
    /**
     * Parameters associated with the machine model
     * @type {Array<CreateParameterDto>}
     * @memberof CreateMachineModelDto
     */
    'parameters': Array<CreateParameterDto>;
    /**
     * Additional parameters for the machine model
     * @type {Array<CreateAdditionalParameterDto>}
     * @memberof CreateMachineModelDto
     */
    'additionalParameters': Array<CreateAdditionalParameterDto>;
    /**
     * Training examples for the machine model
     * @type {Array<CreateExamplePromptDto>}
     * @memberof CreateMachineModelDto
     */
    'trainingExamples': Array<CreateExamplePromptDto>;
}
/**
 * 
 * @export
 * @interface CreateParameterDto
 */
export interface CreateParameterDto {
    /**
     * The name of the parameter
     * @type {string}
     * @memberof CreateParameterDto
     */
    'name': string;
    /**
     * The description of the parameter
     * @type {string}
     * @memberof CreateParameterDto
     */
    'description': string;
    /**
     * The default value of the parameter
     * @type {string}
     * @memberof CreateParameterDto
     */
    'default_value': string;
    /**
     * The ID of the machine model associated with this parameter
     * @type {string}
     * @memberof CreateParameterDto
     */
    'machineModelId': string;
}

/**
 * AgentsApi - axios parameter creator
 * @export
 */
export const AgentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreateMachineAgentDto} createMachineAgentDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentManagementControllerCreateNewAgent: async (createMachineAgentDto: CreateMachineAgentDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createMachineAgentDto' is not null or undefined
            assertParamExists('agentManagementControllerCreateNewAgent', 'createMachineAgentDto', createMachineAgentDto)
            const localVarPath = `/agents`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createMachineAgentDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentManagementControllerDeleteAgent: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('agentManagementControllerDeleteAgent', 'id', id)
            const localVarPath = `/agents/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentManagementControllerGetAllAgents: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/agents`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentManagementControllerUpdateMachineAgent: async (id: string, body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('agentManagementControllerUpdateMachineAgent', 'id', id)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('agentManagementControllerUpdateMachineAgent', 'body', body)
            const localVarPath = `/agents/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AgentsApi - functional programming interface
 * @export
 */
export const AgentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AgentsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CreateMachineAgentDto} createMachineAgentDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentManagementControllerCreateNewAgent(createMachineAgentDto: CreateMachineAgentDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentManagementControllerCreateNewAgent(createMachineAgentDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentsApi.agentManagementControllerCreateNewAgent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentManagementControllerDeleteAgent(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentManagementControllerDeleteAgent(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentsApi.agentManagementControllerDeleteAgent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentManagementControllerGetAllAgents(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentManagementControllerGetAllAgents(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentsApi.agentManagementControllerGetAllAgents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentManagementControllerUpdateMachineAgent(id: string, body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentManagementControllerUpdateMachineAgent(id, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentsApi.agentManagementControllerUpdateMachineAgent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AgentsApi - factory interface
 * @export
 */
export const AgentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AgentsApiFp(configuration)
    return {
        /**
         * 
         * @param {CreateMachineAgentDto} createMachineAgentDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentManagementControllerCreateNewAgent(createMachineAgentDto: CreateMachineAgentDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.agentManagementControllerCreateNewAgent(createMachineAgentDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentManagementControllerDeleteAgent(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.agentManagementControllerDeleteAgent(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentManagementControllerGetAllAgents(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.agentManagementControllerGetAllAgents(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentManagementControllerUpdateMachineAgent(id: string, body: object, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.agentManagementControllerUpdateMachineAgent(id, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AgentsApi - object-oriented interface
 * @export
 * @class AgentsApi
 * @extends {BaseAPI}
 */
export class AgentsApi extends BaseAPI {
    /**
     * 
     * @param {CreateMachineAgentDto} createMachineAgentDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AgentsApi
     */
    public agentManagementControllerCreateNewAgent(createMachineAgentDto: CreateMachineAgentDto, options?: RawAxiosRequestConfig) {
        return AgentsApiFp(this.configuration).agentManagementControllerCreateNewAgent(createMachineAgentDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AgentsApi
     */
    public agentManagementControllerDeleteAgent(id: string, options?: RawAxiosRequestConfig) {
        return AgentsApiFp(this.configuration).agentManagementControllerDeleteAgent(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AgentsApi
     */
    public agentManagementControllerGetAllAgents(options?: RawAxiosRequestConfig) {
        return AgentsApiFp(this.configuration).agentManagementControllerGetAllAgents(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AgentsApi
     */
    public agentManagementControllerUpdateMachineAgent(id: string, body: object, options?: RawAxiosRequestConfig) {
        return AgentsApiFp(this.configuration).agentManagementControllerUpdateMachineAgent(id, body, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ManifestApi - axios parameter creator
 * @export
 */
export const ManifestApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelManagementManifestControllerGetManifest: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/manifest`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ManifestApi - functional programming interface
 * @export
 */
export const ManifestApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ManifestApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modelManagementManifestControllerGetManifest(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modelManagementManifestControllerGetManifest(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ManifestApi.modelManagementManifestControllerGetManifest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ManifestApi - factory interface
 * @export
 */
export const ManifestApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ManifestApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelManagementManifestControllerGetManifest(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.modelManagementManifestControllerGetManifest(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ManifestApi - object-oriented interface
 * @export
 * @class ManifestApi
 * @extends {BaseAPI}
 */
export class ManifestApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ManifestApi
     */
    public modelManagementManifestControllerGetManifest(options?: RawAxiosRequestConfig) {
        return ManifestApiFp(this.configuration).modelManagementManifestControllerGetManifest(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ModelsApi - axios parameter creator
 * @export
 */
export const ModelsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreateMachineModelDto} createMachineModelDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelManagementControllerCreateNewModel: async (createMachineModelDto: CreateMachineModelDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createMachineModelDto' is not null or undefined
            assertParamExists('modelManagementControllerCreateNewModel', 'createMachineModelDto', createMachineModelDto)
            const localVarPath = `/models`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createMachineModelDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelManagementControllerDeleteModel: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('modelManagementControllerDeleteModel', 'id', id)
            const localVarPath = `/models/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelManagementControllerGetAllModels: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/models`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {CreateMachineModelDto} createMachineModelDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelManagementControllerUpdateMachineModel: async (id: string, createMachineModelDto: CreateMachineModelDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('modelManagementControllerUpdateMachineModel', 'id', id)
            // verify required parameter 'createMachineModelDto' is not null or undefined
            assertParamExists('modelManagementControllerUpdateMachineModel', 'createMachineModelDto', createMachineModelDto)
            const localVarPath = `/models/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createMachineModelDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ModelsApi - functional programming interface
 * @export
 */
export const ModelsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ModelsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CreateMachineModelDto} createMachineModelDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modelManagementControllerCreateNewModel(createMachineModelDto: CreateMachineModelDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modelManagementControllerCreateNewModel(createMachineModelDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelsApi.modelManagementControllerCreateNewModel']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modelManagementControllerDeleteModel(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modelManagementControllerDeleteModel(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelsApi.modelManagementControllerDeleteModel']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modelManagementControllerGetAllModels(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modelManagementControllerGetAllModels(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelsApi.modelManagementControllerGetAllModels']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {CreateMachineModelDto} createMachineModelDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modelManagementControllerUpdateMachineModel(id: string, createMachineModelDto: CreateMachineModelDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modelManagementControllerUpdateMachineModel(id, createMachineModelDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModelsApi.modelManagementControllerUpdateMachineModel']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ModelsApi - factory interface
 * @export
 */
export const ModelsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ModelsApiFp(configuration)
    return {
        /**
         * 
         * @param {CreateMachineModelDto} createMachineModelDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelManagementControllerCreateNewModel(createMachineModelDto: CreateMachineModelDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.modelManagementControllerCreateNewModel(createMachineModelDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelManagementControllerDeleteModel(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.modelManagementControllerDeleteModel(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelManagementControllerGetAllModels(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.modelManagementControllerGetAllModels(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {CreateMachineModelDto} createMachineModelDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modelManagementControllerUpdateMachineModel(id: string, createMachineModelDto: CreateMachineModelDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.modelManagementControllerUpdateMachineModel(id, createMachineModelDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ModelsApi - object-oriented interface
 * @export
 * @class ModelsApi
 * @extends {BaseAPI}
 */
export class ModelsApi extends BaseAPI {
    /**
     * 
     * @param {CreateMachineModelDto} createMachineModelDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelsApi
     */
    public modelManagementControllerCreateNewModel(createMachineModelDto: CreateMachineModelDto, options?: RawAxiosRequestConfig) {
        return ModelsApiFp(this.configuration).modelManagementControllerCreateNewModel(createMachineModelDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelsApi
     */
    public modelManagementControllerDeleteModel(id: string, options?: RawAxiosRequestConfig) {
        return ModelsApiFp(this.configuration).modelManagementControllerDeleteModel(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelsApi
     */
    public modelManagementControllerGetAllModels(options?: RawAxiosRequestConfig) {
        return ModelsApiFp(this.configuration).modelManagementControllerGetAllModels(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {CreateMachineModelDto} createMachineModelDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ModelsApi
     */
    public modelManagementControllerUpdateMachineModel(id: string, createMachineModelDto: CreateMachineModelDto, options?: RawAxiosRequestConfig) {
        return ModelsApiFp(this.configuration).modelManagementControllerUpdateMachineModel(id, createMachineModelDto, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ServerLiveStatusApi - axios parameter creator
 * @export
 */
export const ServerLiveStatusApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetStatus: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ServerLiveStatusApi - functional programming interface
 * @export
 */
export const ServerLiveStatusApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ServerLiveStatusApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appControllerGetStatus(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appControllerGetStatus(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServerLiveStatusApi.appControllerGetStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ServerLiveStatusApi - factory interface
 * @export
 */
export const ServerLiveStatusApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ServerLiveStatusApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetStatus(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.appControllerGetStatus(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ServerLiveStatusApi - object-oriented interface
 * @export
 * @class ServerLiveStatusApi
 * @extends {BaseAPI}
 */
export class ServerLiveStatusApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServerLiveStatusApi
     */
    public appControllerGetStatus(options?: RawAxiosRequestConfig) {
        return ServerLiveStatusApiFp(this.configuration).appControllerGetStatus(options).then((request) => request(this.axios, this.basePath));
    }
}



